/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bankcoquette;

import javax.print.attribute.standard.JobImpressions;
import javax.swing.*;

/**
 *
 * @author Acer
 */
public class BankGUI extends javax.swing.JFrame {
    
    private JTextArea textArea = new JTextArea(20,40);
    private BankCoquette banco;

    /**
     * Creates new form BankGUI
     */
    public BankGUI() {
        banco = new BankCoquette();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAtenderSolicitudes = new javax.swing.JButton();
        btnCambioDivisas = new javax.swing.JButton();
        btnDarBajaMillonarios = new javax.swing.JButton();
        btnVerificarCuenta = new javax.swing.JButton();
        btnEliminarCuenta = new javax.swing.JButton();
        btnCrearCuenta1 = new javax.swing.JButton();
        btnExtraccion = new javax.swing.JButton();
        btnDeposito = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(246, 202, 225));

        jPanel1.setBackground(new java.awt.Color(252, 172, 208));
        jPanel1.setPreferredSize(new java.awt.Dimension(349, 100));

        jLabel1.setFont(new java.awt.Font("Script MT Bold", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Banco Coquette");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnAtenderSolicitudes.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        btnAtenderSolicitudes.setText("Atender Solicitudes");
        btnAtenderSolicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtenderSolicitudesActionPerformed(evt);
            }
        });

        btnCambioDivisas.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        btnCambioDivisas.setText("Cambio de Divisas");
        btnCambioDivisas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambioDivisasActionPerformed(evt);
            }
        });

        btnDarBajaMillonarios.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        btnDarBajaMillonarios.setText("Dar de Baja a Millonarios");
        btnDarBajaMillonarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarBajaMillonariosActionPerformed(evt);
            }
        });

        btnVerificarCuenta.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        btnVerificarCuenta.setText("Verificar Cuenta");
        btnVerificarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarCuentaActionPerformed(evt);
            }
        });

        btnEliminarCuenta.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        btnEliminarCuenta.setText("Eliminar Cuenta");
        btnEliminarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCuentaActionPerformed(evt);
            }
        });

        btnCrearCuenta1.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        btnCrearCuenta1.setText("Crear Cuenta");
        btnCrearCuenta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuenta1ActionPerformed(evt);
            }
        });

        btnExtraccion.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        btnExtraccion.setText("Extraccion");
        btnExtraccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtraccionActionPerformed(evt);
            }
        });

        btnDeposito.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        btnDeposito.setText("Deposito");
        btnDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDarBajaMillonarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCambioDivisas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAtenderSolicitudes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDeposito, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(btnVerificarCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearCuenta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExtraccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
                .addContainerGap())
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearCuenta1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnAtenderSolicitudes, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                        .addComponent(btnVerificarCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(49, 49, 49)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDarBajaMillonarios, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCambioDivisas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExtraccion, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtenderSolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenderSolicitudesActionPerformed
        // Crear los componentes para capturar los datos de la solicitud
        JTextField txtNumeroIdentidad = new JTextField();
        JTextField txtNumeroCuenta = new JTextField();
        JTextField txtCantidad = new JTextField();
        String[] opciones = {"Depósito", "Extracción"};
        JComboBox<String> cmbTipo = new JComboBox<>(opciones);
    
        // Crear el panel para los campos de entrada
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        panel.add(new JLabel("Número de Identidad:"));
        panel.add(txtNumeroIdentidad);
        panel.add(new JLabel("Número de Cuenta:"));
        panel.add(txtNumeroCuenta);
        panel.add(new JLabel("Cantidad:"));
        panel.add(txtCantidad);
        panel.add(new JLabel("Tipo de Solicitud:"));
        panel.add(cmbTipo);
    
        // Mostrar ventana emergente
        int result = JOptionPane.showConfirmDialog(null, panel, "Atender Solicitud",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
    
        // Procesar la solicitud si se presiona OK
        if (result == JOptionPane.OK_OPTION) {
            // Obtener los datos ingresados por el usuario
            String numeroIdentidad = txtNumeroIdentidad.getText();
            int numeroCuenta = Integer.parseInt(txtNumeroCuenta.getText());
            double cantidad = Double.parseDouble(txtCantidad.getText());
            String tipo = cmbTipo.getSelectedItem().toString();
        
            // Crear y atender la solicitud
            Solicitud solicitud = new Solicitud("Deposito", numeroIdentidad,cantidad,"","","","","",numeroCuenta);
            banco.atenderSolicitud(solicitud);
        }
    }//GEN-LAST:event_btnAtenderSolicitudesActionPerformed

    private void btnCambioDivisasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambioDivisasActionPerformed
        // Crear los componentes para capturar los datos del cliente
        JTextField txtCantidad = new JTextField();
        JTextField txtNumID = new JTextField();
        JComboBox<String> cmbTipoDivisa = new JComboBox<>();
        cmbTipoDivisa.addItem("Dólar");
        cmbTipoDivisa.addItem("Euro");
        cmbTipoDivisa.addItem("Libra");
    
        // Crear el panel para los campos de entrada
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        panel.add(new JLabel("Cantidad en Divisa:"));
        panel.add(txtCantidad);
        panel.add(new JLabel("Número de Identidad:"));
        panel.add(txtNumID);
        panel.add(new JLabel("Tipo de Divisa:"));
        panel.add(cmbTipoDivisa);
    
        // Mostrar ventana emergente
        int result = JOptionPane.showConfirmDialog(null, panel, "Cambio de Divisas",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
    
        // Procesar la solicitud si se presiona OK
        if (result == JOptionPane.OK_OPTION) {
            // Obtener los datos ingresados por el usuario
            double cantidad = Double.parseDouble(txtCantidad.getText());
            String numID = txtNumID.getText();
            String tipoDivisa = cmbTipoDivisa.getSelectedItem().toString();
        
            // Realizar el cambio de divisas
            banco.cambioDivisas(cantidad, numID, tipoDivisa);
        }
    }//GEN-LAST:event_btnCambioDivisasActionPerformed

    private void btnDarBajaMillonariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarBajaMillonariosActionPerformed
        ListaSE<CAhorro> millonarios = banco.DarBajaAMillonarios();
        for (int i = 0; i < millonarios.Longitud(); i++) {
            CAhorro cuenta = millonarios.Obtener(i);
            JOptionPane.showMessageDialog(null, "Cuenta dada de baja: " + cuenta.getNumID());
        }
    }//GEN-LAST:event_btnDarBajaMillonariosActionPerformed

    private void btnVerificarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarCuentaActionPerformed
        int result = banco.VerificarCuenta();
        if (result == -1) {
            JOptionPane.showMessageDialog(null, "No hay solicitudes en espera");
        } else {
            JOptionPane.showMessageDialog(null, "La cuenta esta en la posicion: " + result);
        }
    }//GEN-LAST:event_btnVerificarCuentaActionPerformed

    private void btnEliminarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCuentaActionPerformed
        JTextField numIdentField = new JTextField(10);
        
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel,BoxLayout.Y_AXIS));
        panel.add(new JLabel("Ingrese el numero de identidad de la cuenta que quiere eliminar:"));
        panel.add(numIdentField);
        
        int result = JOptionPane.showConfirmDialog(null, panel,"Agregar Solicitud",
                     JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);
        
        if (result == JOptionPane.OK_OPTION) {
            //Numero del usuario
            String numIdentidad = numIdentField.getText();
            
            //Buscar cuenta
            boolean cuentaEncontrada = false;
            for (int i = 0; i < banco.cuentas.Longitud(); i++) {
                CAhorro cuenta = banco.cuentas.Obtener(i);
                if (cuenta.getNumID().equals(numIdentidad)) {
                    //Eliminar cuenta
                    banco.cuentas.Eliminar(i);
                    JOptionPane.showMessageDialog(null, "Cuenta eliminada exitosamente");
                    cuentaEncontrada = true;
                    break;
                }
            }
            //Mensaje si no la encuente
            if (!cuentaEncontrada) {
                JOptionPane.showMessageDialog(null, "No se encontro ninguna cuenta con el numero de identidad proporcionado", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarCuentaActionPerformed

    private void btnCrearCuenta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuenta1ActionPerformed
        JTextField numId = new JTextField();
        JTextField saldo = new JTextField();
        
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel,BoxLayout.Y_AXIS));
        panel.add(new JLabel("Numero de Identidad: "));
        panel.add(numId);
        panel.add(new JLabel("Saldo: "));
        panel.add(saldo);
        
        //Panel de dialogo
        int result = JOptionPane.showConfirmDialog(null, panel,"Crear",
                     JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);
        
        //Ver si se hizo cloc en OK
        if (result == JOptionPane.OK_OPTION) {
            //Datos de usuario
            String numIdentidad = numId.getText();
            double saldoCuenta;
            try {
                saldoCuenta = Double.parseDouble(saldo.getText());
                
                //Crear solicitud
                CAhorro nuevaCuenta = new CAhorro(numIdentidad, 0);
                banco.agregarCuenta(nuevaCuenta); // Agrega cuenta al banco
                JOptionPane.showMessageDialog(null, "Cuenta creada correctamente");
            } catch (NumberFormatException exception) {
                JOptionPane.showMessageDialog(null, "La saldo deber ser un numero valido","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCrearCuenta1ActionPerformed

    private void btnExtraccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtraccionActionPerformed
        // Obtener datos
        JTextField txtNombre = new JTextField();
        JTextField txtApellidos = new JTextField();
        JTextField txtNumeroIdentidad = new JTextField();
        JTextField txtSexo = new JTextField();
        JTextField txtNacionalidad = new JTextField();
        JTextField txtDireccion = new JTextField();
        JTextField txtNumeroCuenta = new JTextField();
        JTextField txtCantidad = new JTextField();
    
        // Crear el panel 
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        panel.add(new JLabel("Nombre:"));
        panel.add(txtNombre);
        panel.add(new JLabel("Apellidos:"));
        panel.add(txtApellidos);
        panel.add(new JLabel("Número de Identidad:"));
        panel.add(txtNumeroIdentidad);
        panel.add(new JLabel("Sexo:"));
        panel.add(txtSexo);
        panel.add(new JLabel("Número de Cuenta:"));
        panel.add(txtNumeroCuenta);
        panel.add(new JLabel("Cantidad a Extraer:"));
        panel.add(txtCantidad);
    
        // Mostrar campo solo si es extranjero
        int isForeigner = JOptionPane.showConfirmDialog(null, "¿Es usted extranjero?", "Confirmar",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (isForeigner == JOptionPane.YES_OPTION) {
            panel.add(new JLabel("Nacionalidad:"));
            panel.add(txtNacionalidad);
            panel.add(new JLabel("Dirección:"));
            panel.add(txtDireccion);
        }
    
        // Mostrar ventana
        int result = JOptionPane.showConfirmDialog(null, panel, "Solicitud de Extracción",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
    
        // Procesar la solicitud
        if (result == JOptionPane.OK_OPTION) {
            // Obtener los datos ingresados por el usuario
            String nombre = txtNombre.getText();
            String apellidos = txtApellidos.getText();
            String numeroIdentidad = txtNumeroIdentidad.getText();
            String sexo = txtSexo.getText();
            String nacionalidad = txtNacionalidad.getText();
            String direccion = txtDireccion.getText();
            int numeroCuenta = Integer.parseInt(txtNumeroCuenta.getText());
            double cantidad = Double.parseDouble(txtCantidad.getText());
        
            // Crear y atender la solicitud de extracción
            Solicitud solicitud = new Solicitud("Deposito", numeroIdentidad,cantidad,nombre,apellidos,sexo,"","",numeroCuenta);
            banco.atenderSolicitud(solicitud);
        }
    }//GEN-LAST:event_btnExtraccionActionPerformed

    private void btnDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositoActionPerformed
        // Obtener datos
        JTextField txtNombre = new JTextField();
        JTextField txtApellidos = new JTextField();
        JTextField txtNumeroIdentidad = new JTextField();
        JTextField txtSexo = new JTextField();
        JTextField txtNacionalidad = new JTextField();
        JTextField txtDireccion = new JTextField();
        JTextField txtNumeroCuenta = new JTextField();
        JTextField txtCantidad = new JTextField();
    
        // Crear el panel 
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        panel.add(new JLabel("Nombre:"));
        panel.add(txtNombre);
        panel.add(new JLabel("Apellidos:"));
        panel.add(txtApellidos);
        panel.add(new JLabel("Número de Identidad:"));
        panel.add(txtNumeroIdentidad);
        panel.add(new JLabel("Sexo:"));
        panel.add(txtSexo);
        panel.add(new JLabel("Número de Cuenta:"));
        panel.add(txtNumeroCuenta);
        panel.add(new JLabel("Cantidad a Depositar:"));
        panel.add(txtCantidad);
    
        // Mostrar campo solo si es extranjero
        int isForeigner = JOptionPane.showConfirmDialog(null, "¿Es usted extranjero?", "Confirmar",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (isForeigner == JOptionPane.YES_OPTION) {
            panel.add(new JLabel("Nacionalidad:"));
            panel.add(txtNacionalidad);
            panel.add(new JLabel("Dirección:"));
            panel.add(txtDireccion);
        }
    
        // Mostrar ventana
        int result = JOptionPane.showConfirmDialog(null, panel, "Solicitud de Depósito",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
    
        // Procesar la solicitud
        if (result == JOptionPane.OK_OPTION) {
            // Obtener los datos ingresados por el usuario
            String nombre = txtNombre.getText();
            String apellidos = txtApellidos.getText();
            String numeroIdentidad = txtNumeroIdentidad.getText();
            String sexo = txtSexo.getText();
            String nacionalidad = txtNacionalidad.getText();
            String direccion = txtDireccion.getText();
            int numeroCuenta = Integer.parseInt(txtNumeroCuenta.getText());
            double cantidad = Double.parseDouble(txtCantidad.getText());
            
            Solicitud solicitud = new Solicitud("Deposito", numeroIdentidad,cantidad,nombre,apellidos,sexo,"","",numeroCuenta);
            banco.atenderSolicitud(solicitud);
        }
    }//GEN-LAST:event_btnDepositoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton btnAtenderSolicitudes;
    private javax.swing.JButton btnCambioDivisas;
    private javax.swing.JButton btnCrearCuenta1;
    private javax.swing.JButton btnDarBajaMillonarios;
    private javax.swing.JButton btnDeposito;
    private javax.swing.JButton btnEliminarCuenta;
    private javax.swing.JButton btnExtraccion;
    private javax.swing.JButton btnVerificarCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
